### ISSUE TITLE
Bugs with cage porosity model

### ISSUE THREAD

**Issue by dandavies99** [ImperialCollegeLondon/SupraShare#4]
The current idea is to use the cage porosity model (see [this branch](https://github.com/ImperialCollegeLondon/SupraShare/tree/add-cage-model)) as an example in this repo as a template. 

There appear to be various problems setting up a python env for the [current implemented website app](https://github.com/lukasturcani/cage_prediction/tree/master/website). Possibly specific versions of scikit-learn aren't compatible with packages being installed via pip (which have no version specified) or a specific version of python. 

**Proposed solution** - have a look at the version running on a local workstation (which presumably is running bug-free) and compare.

**Comment by AdrianDAlessandro** [comment]
I believe this is sorted. We haven't confirmed the environment is identical to their local version, but it is currently running as expected.

**Comment by dandavies99** [comment]
Yes we got to the bottom of this
