### ISSUE TITLE
Improve cage porosity model app

### ISSUE THREAD

**Issue by dandavies99** [ImperialCollegeLondon/SupraShare#7]
The current cage porosity model app is a placeholder to be improved. 

TODO

- [x] Replace the manually written front end HTML and javascript with a (hopefully simple) Dash app.
- [x] Allow for other input types: (i) file upload (.mol) (ii) drawing a structure using [jsml](https://dash.plotly.com/dash-bio/jsme) or similar, if possible.

**Comment by dandavies99** [comment]
Nice to haves for usability:
- [x] Have a preview (plot) of the molecule after uploading as sanity check that it has uploaded correctly.
- [x] (Possibly advanced) preview the uploaded molecule in the editor (jsml) to manually edit the atoms of an existing molecule.

**Comment by AdrianDAlessandro** [comment]
Example previewing a molecule in Dash: https://iwatobipen.wordpress.com/2019/02/16/make-interactive-dashboard-with-dash2-chemoinformatcs-rdkit/
